resolver: lts-19.30

packages:
  - oneshot
  - stellar-horizon
  - veche-web
  - withcallstack
  - yesod-auth-stellar
  - yesod-form-bootstrap5

extra-deps:
  # stellar-horizon:exe
    - github: cblp/servant-cli
      commit: 929da900e2a6526450e846e7182b3df6bc989209
      # https://github.com/mstksg/servant-cli/pull/3
  # stellar-sdk
    - DRBG-0.5.5
  # veche-web
    - github: cblp/haskell-telegram-api
      commit: 8c369af6a560cb3cf842068ab7c291dea8d5e2b8
      # https://github.com/klappvisor/haskell-telegram-api/pull/133
  # yesod-auth-stellar
    - github: cblp/haskell-stellar-sdk
      commit: 958c11f0ecafc5e80751c76c656964dc1ef42b6e
      # https://github.com/teequoo/haskell-stellar-sdk/pull/2
