approot: https://e35e-109-228-117-123.eu.ngrok.io
database:
  database: veche.sqlite3
database-migrate: false
development: true
escrow-file: escrow.json
session-key-file: config/client_session_key.aes
telegram-bot-name: veche_test_bot
telegram-bot-notify-whitelist: [cblp_su]
