FEDERATION_SERVER="https://veche.montelibero.org/stellar-federation"

[[CURRENCIES]]
code="VECHE"
issuer="GDUMR6C3XNIMXUCS3WR7DZDWWDWAGRCCNZ23FWXAMKAIYOGKS7KN47AG"
# status="live"
# display_decimals=7
# anchor_asset_type="other"
# is_asset_anchored=false
# name="VECHE"
# desc="VECHE is a token that gi–ºes its owner the power over the Veche enterprise."
