NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"
FEDERATION_SERVER="https://veche.montelibero.org/stellar-federation"
WEB_AUTH_ENDPOINT="https://veche.montelibero.org/stellar-auth"

[[CURRENCIES]]
code="VECHE"
issuer="GDUMR6C3XNIMXUCS3WR7DZDWWDWAGRCCNZ23FWXAMKAIYOGKS7KN47AG"

[DOCUMENTATION]
ORG_NAME="Veche/Veće/Вече/Веће"
